#!/system/bin/sh
BASEDIR=$(dirname "$0")
DEX="$BASEDIR"/rish_shizuku.dex

if [ ! -f "$DEX" ]; then
  echo "Cannot find $DEX, please check the tutorial in Shizuku app"
  exit 1
fi

if [ $(getprop ro.build.version.sdk) -ge 34 ]; then
  if [ -w $DEX ]; then
    echo "On Android 14+, app_process cannot load writable dex."
    echo "Attempting to remove the write permission..."
    chmod 400 $DEX
    if [ -w $DEX ]; then
      echo "Cannot remove the write permission of $DEX."
      echo "You can copy to file to terminal app's private directory (/data/data/<package>, so that remove write permission is possible"
      exit 1
    else
      echo "Write permission was removed successfully."
    fi
  fi
fi

# Replace "PKG" with the application id of your terminal app and "moe.shizuku.privileged.api" with the application id of Shizuku
[ -z "$RISH_APPLICATION_ID" ] && export RISH_APPLICATION_ID="com.termux" && export MANAGER_APPLICATION_ID="moe.shizuku.privileged.api"
/system/bin/app_process -Djava.class.path="$DEX" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
